# Generated by Django 5.1.5 on 2025-05-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('watched_till', models.IntegerField(help_text='In seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
