# Generated by Django 5.1.5 on 2025-04-24 15:23

import django.db.models.deletion
import django.utils.timezone
import presentation.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=255)),
                ('pdata', models.JSONField(default=presentation.models.default_slide, help_text='Stores all slide data in JSON format')),
                ('theme', models.CharField(default='default', max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('can_download', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_allowed_users', models.ManyToManyField(blank=True, related_name='shared_presentations', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to=settings.AUTH_USER_MODEL)),
                ('req_for_access', models.ManyToManyField(blank=True, related_name='requested_presentations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
